fix: race condition causes "AttributeError: 'tqdm' object has no attribute 'pos'"
cls._instances were being generated asynchronously and tqdm._get_free_pos
was being called between __new__ and __init__. _get_free_pos was accessing
the tqdm.pos attribute which was going to be set in __init__.

Fixed this by setting instance.pos = 0 in __new__ which will then be
corrected in __init__.